### ISSUE TITLE
How are the targets constructed?

### ISSUE THREAD

**Issue by arxyzan** [Guillem96/data2vec-vision#1]
Hi man. Thanks for your work on Data2Vec. I just reviewed your implementation and noticed that you use the actual image as targets but I think the targets must be discrete as in BEiT. Although I didn't find any info on this in the paper but according to [this answer](https://github.com/pytorch/fairseq/issues/4193#issuecomment-1034036798) from the author, I think the general procedure is same as BEiT, otherwise it would've been mentioned in the paper. What do your think?

**Comment by Guillem96** [comment]
Targets are not discrete.
Paper citation:
>  Moreover, our target representations are continuous
and contextualized, through the use of self-attention, which
makes them richer than a fixed set of targets and/or targets
based on local context such as used in most prior work.

I think the only BEiT like approach that they follow is the image masking, which is the transform that's implemented under the `data2vec_vision/transforms.py` file

**Comment by arxyzan** [comment]
Yes you're exactly right. I just noticed it yesterday thanks
